from __future__ import annotations

SUBCATEGORIES_BY_BUCKET: dict[int, tuple[str, ...]] = {
    1: (
        "Architecture & Design (ADRs, system diagrams, RFCs)",
        "Product Requirements (PRDs, feature specs, user stories)",
        "Source Code & Commits",
        "Pull Requests & Code Reviews",
        "Issue Tracking (bugs, features, tasks)",
        "API Documentation (OpenAPI, GraphQL schemas)",
        "Sprint Artifacts (planning, standups, retros)",
        "Infrastructure & IaC (Terraform, K8s, Helm)",
        "CI/CD Pipelines & Configs",
        "Engineering Wikis & Runbooks",
        "Testing & QA (test plans, automation)",
        "Postmortems / Incident Reports",
        "Security Reviews & Threat Models",
        "Model Development & Research (model cards, research notes, training recipes, fine-tuning configs)",
        "Experiments & Training Runs (W&B/MLflow logs, hyperparameter sweeps, checkpoints, compute reports)",
        "Datasets & Data Pipelines (dataset cards, annotation guidelines, preprocessing, versioning, lineage)",
        "Evaluation & Benchmarking (eval harnesses, benchmark results, human evals, regression tests)",
        "Safety, Alignment & Red-teaming (red-team reports, safety evals, bias audits, jailbreak logs)",
        "Prompts & Behavior Specs (system prompts, prompt templates, persona specs, tool-use schemas)",
        "Inference & Serving (serving configs, latency benchmarks, GPU topology, quantization)",
        "MLOps & ML Platform (model registry, training orchestration, drift monitoring, model CI/CD)",
        "Agents & Retrieval Systems (agent architectures, vector DB configs, retrieval evals, tool definitions)",
        "AI Governance & Responsible AI (ethics reviews, release sign-offs, regulatory compliance, scaling policies)",
        "Other / General",
    ),
    2: (
        "CRM Records (accounts, contacts, deal stages)",
        "Sales Call Transcripts (discovery, demo, closing)",
        "Customer Email Threads",
        "Support Tickets & Resolutions",
        "Proposals, Quotes & SOWs",
        "Win/Loss Analysis",
        "NPS / CSAT / Survey Responses",
        "Customer Onboarding Docs",
        "QBR / Account Reviews",
        "Sales Playbooks & Battlecards",
        "Demo Recordings",
        "Customer Interviews & Discovery Notes",
        "Churn / Cancellation Notes",
        "Other / General",
    ),
    3: (
        "Board Decks & Board Minutes",
        "OKRs / KPIs (current and historical)",
        "Competitive Analysis & Battlecards",
        "Investor Memos & Updates",
        "Market Research & Sizing",
        "Annual / Quarterly Strategic Plans",
        "Pivot Documentation",
        "Vision, Mission, Values",
        "Business Model & Unit Economics",
        "Product / Company Roadmaps",
        "M&A / Due Diligence",
        "SWOT & Scenario Planning",
        "Other / General",
    ),
    4: (
        "Financial Statements (P&L, BS, Cash Flow)",
        "Customer Contracts & MSAs",
        "Vendor & Partner Agreements",
        "Invoices, AR/AP",
        "Cap Table & Equity Records",
        "R&D and Tax Filings",
        "Compliance Documentation (SOC2, ISO, GDPR, DPDP)",
        "Due Diligence Q&A",
        "NDAs & MNDAs",
        "Insurance & Risk",
        "Audit Reports",
        "Banking & Treasury Records",
        "IP, Patents, Trademarks",
        "Litigation & Disputes",
        "Other / General",
    ),
    5: (
        "SOPs & Process Documentation",
        "Hiring Pipelines (JDs, scorecards, interview notes)",
        "Offer Letters & Employment Contracts",
        "Onboarding Documents & Checklists",
        "Performance Reviews & 360s",
        "Compensation, Benefits & Payroll",
        "Equity / ESOP Plans",
        "Policy Documents (handbook, code of conduct)",
        "Training Materials & L&D",
        "Operational Vendor Contracts",
        "Facilities & IT Ops",
        "Org Charts & Headcount Plans",
        "Employee Lifecycle (transfers, exits)",
        "Other / General",
    ),
    6: (
        "Campaign Briefs",
        "Ad Copy & Creative Assets",
        "Performance Reports (CTR, CPA, ROAS, conversion)",
        "Brand Guidelines",
        "Content Calendars",
        "Email Sequences & Newsletters",
        "A/B Test Logs & Experiments",
        "Press Releases & PR Coverage",
        "Blog Posts & SEO Content",
        "Social Media Content & Calendars",
        "Webinar / Event Content",
        "Case Studies & Testimonials",
        "Landing Pages & Microsites",
        "Influencer / Partnership Content",
        "Other / General",
    ),
    7: (
        "Decision Logs",
        "Action Items & Follow-ups",
        "Slack / Teams Channel Exports (by channel type: leadership, eng, sales, random)",
        "Internal Memos & Announcements",
        "All-Hands & Town Hall Notes",
        "Retrospectives (project, sprint, quarterly)",
        "Board Discussion Threads (between meetings)",
        "1:1 Meeting Notes",
        "Cross-functional Sync Notes",
        "Async Video Transcripts (Loom, Vidyard)",
        "Internal Email Broadcasts",
        "DM / Group Chat Exports (with consent + redaction)",
        "Other / General",
    ),
}


def labels_for_bucket(bucket_number: int | None) -> tuple[str, ...]:
    if bucket_number is None:
        return ()
    try:
        bn = int(bucket_number)
    except (TypeError, ValueError):
        return ()
    return SUBCATEGORIES_BY_BUCKET.get(bn, ())
